@startuml
title 1P 주문 flow

[*] -> 장바구니: 메뉴 담기

state Order {
  장바구니 -> 주문: 주문 하기

  주문 --> 결제: 결제 수단 선택
  결제: 결제 하기

  결제 --> 주문접수대기: 결제 완료
  주문접수대기: 접수 대기중

  결제 -> 실패: 결제 실패

  실패 --> 주문: 다시 시도

  주문접수대기 --> 주문접수: 주문 접수 목록
  주문접수: 사장님 주문접수
}

주문접수대기 --> 취소: 주문자 취소

주문접수 -> 취소: 사장님 취소

취소 ---> [*]: 취소된 주문

state Delivery {
  주문접수 --> 배차: 조리 중
  배차: 라이더 배차

  배차 -> 취소: 배차 실패
  취소: 주문 취소

  배차 --> 배달: 라이더 픽업
  배달: 라이더 배달

  배달 --> 고객: 라이더 배달 중
  고객: 배달 완료
}

고객 -> [*]: 주문 처리 성공
@enduml
