@startmindmap
title 주문 도메인 모델

*[#lightblue] 주문(어그리거트)

--[#lightblue] 결제(어그리거트)
--- 주문ID
--- 결제수단
--- 결제금액
--- ...

--[#lightblue] 장바구니(어그리거트)
--- 주문회원
--- 가게
--- 주문상품
---- 메뉴
----- 가격
----- 할인정보
----- 옵션
------ 가격
------ ...
----- ...

** 주문회원
*** 주문ID
*** 연락처
*** 배송주소
*** ...

** 가게
*** ...

** 라이더
*** ...

** 요청정보
*** 내용
*** 대상
*** ...

** 프로모션
*** 타입
*** 프로모션 ID
*** 할인금액
*** 할인율
*** ...

center footer By B-Team
@endmindmap
