@startuml
'skinparam classAttributeIconSize 0
interface 사용조건{
}

class 최소주문금액_사용조건 {
}


interface 사용대상_사용조건{
}


class 태그_대상_사용조건{

}

class 메뉴_대상_사용조건{
}

class 사용조건그룹{

}

사용조건그룹 o-- 사용조건

사용조건 <|.. 최소주문금액_사용조건
사용조건 <|.. 사용대상_사용조건

사용대상_사용조건 <|.. 태그_대상_사용조건
사용대상_사용조건 <|.. 메뉴_대상_사용조건
사용대상_사용조건 <|.. 가게_대상_사용조건


class 캠페인_마스터쿠폰{
    {field} - 시작일
    {field} - 종료일
    {field} - 쿠폰 타입(personal, mass)
    {field} - 할인 종류(주문 금액, 배달팁, 전체 결제 금액, 상품)
    {field} - 예산

    {method} 쿠폰 생성(팩토리)
    {method} 할인 적용 (retrun 할인에 대한 정보)
    {method} 쿠폰 발급 가능?
    {method} 쿠폰 발급(팩토리)
    '{method} 쿠폰 사용 가능
}

class 캠페인_사용조건그룹_맵핑{

}

사용조건그룹 <-right- 캠페인_사용조건그룹_맵핑

캠페인_마스터쿠폰 <-left- 캠페인_사용조건그룹_맵핑


interface 쿠폰발급유효성정책{
}

interface 발급된_쿠폰_날짜_기간_유효_정책{
}

class 캠페인의날짜로유효정책{
}

class 발행후특정기간유효정책{
}

쿠폰발급유효성정책 <|.. 발급된_쿠폰_날짜_기간_유효_정책
발급된_쿠폰_날짜_기간_유효_정책 <|.. 캠페인의날짜로유효정책
발급된_쿠폰_날짜_기간_유효_정책 <|.. 발행후특정기간유효정책

interface 쿠폰_발급_한도_정책 {

}


class 예산내에서_발급_제한{

}

class 갯수_제한_발급_제한{

}

쿠폰_발급_한도_정책 <|.. 예산내에서_발급_제한
쿠폰_발급_한도_정책 <|.. 갯수_제한_발급_제한

캠페인_마스터쿠폰 --> 쿠폰_발급_한도_정책



캠페인_마스터쿠폰 --> 쿠폰발급유효성정책



interface 할인_정책{
}

class 정액_정책{
    {field} - 할인 금액
}

class 정률_정책{
    {field} - 최대할인금액
    {field} - 비율
}

캠페인_마스터쿠폰 -down-> 할인_정책


interface 코드생성{
}

class 랜덤코드생성{

}

class 직접입력생성{
}

코드생성 <|.. 랜덤코드생성
코드생성 <|.. 직접입력생성

캠페인_마스터쿠폰 --> 코드생성
class 쿠폰{
    {field} - 캠페인_마스터쿠폰 REF
    {field} - 쿠폰 코드

}

class 쿠폰_발급{
    {field} - 쿠폰 REF
    {field} - 회원 REF

    {field} - 시작일(발급된 쿠폰의 발급일)
    {field} - 종료일(발급된 쿠폰의 종료일)
}

class 쿠폰_사용{

}

class 쿠폰_사용_히스토리{
}


'쿠폰 o-down- 쿠폰_발급
쿠폰_발급 --> 쿠폰_사용
쿠폰_발급 o-- 쿠폰_사용_히스토리

할인_정책 <|.. 정액_정책
할인_정책 <|.. 정률_정책

' 캠페인 시작, 종료 쿠폰 생성 가능한 일
' 쿠폰 발급 시작, 종료는 사용 가능 기간
' 쿠폰 생성시 쿠폰 시작일,종료일 발급 정책 필요

@enduml
